export const ActionType={
    SET_PRODUCTS:"SET_PRODUCTS",
    SELECTED_PRODUCT:"SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
    PRODUCT_IMAGE:"PRODUCT_IMAGE",
    ADD_TO_CART:"ADD_TO_CART"
}